# basic configuration
seed: 42
device: "cuda"
data_dir: "../data/train/"
train_file_name: "custom_train_ratings.csv"
valid_file_name: "custom_valid_ratings.csv"
model_dir: "models/"
model_file_name: "best_model.pt"
output_dir: "outputs/"

# train configuration
log_steps: 50
num_workers: 4
n_epochs: 20
batch_size: 4096
patience: 1

# select components
defaults:
  - _self_
  - dataloader: default
  - model: mf
  - loss_function: bce
  - optimizer: adamw
  - scheduler: plateau
